// Auto-generated by parallel_unsplash_photos_search
// Do not edit manually

export const IMAGES = {
  DOCTOR_AVATAR_1: "https://images.unsplash.com/photo-1589987223223-e95a2632bb5a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwyfHxtZW50YWwlMjBoZWFsdGglMjBwcm9mZXNzaW9uYWwlMjBkb2N0b3IlMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzczNjA1NzM2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  DOCTOR_AVATAR_2: "https://images.unsplash.com/photo-1587032154988-52646414698d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwzfHxtZW50YWwlMjBoZWFsdGglMjBwcm9mZXNzaW9uYWwlMjBkb2N0b3IlMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzczNjA1NzM2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  DOCTOR_AVATAR_3: "https://images.unsplash.com/photo-1589987223258-4799a9a0626b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwxfHxtZW50YWwlMjBoZWFsdGglMjBwcm9mZXNzaW9uYWwlMjBkb2N0b3IlMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzczNjA1NzM2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  DOCTOR_AVATAR_4: "https://images.unsplash.com/photo-1696960181436-1b6d9576354e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw2fHxtZW50YWwlMjBoZWFsdGglMjBwcm9mZXNzaW9uYWwlMjBkb2N0b3IlMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzczNjA1NzM2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  DOCTOR_AVATAR_5: "https://images.unsplash.com/photo-1594055363761-7e8b82831649?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw1fHxtZW50YWwlMjBoZWFsdGglMjBwcm9mZXNzaW9uYWwlMjBkb2N0b3IlMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzczNjA1NzM2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  DOCTOR_AVATAR_6: "https://images.unsplash.com/photo-1742436707321-33fed05590bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw0fHxtZW50YWwlMjBoZWFsdGglMjBwcm9mZXNzaW9uYWwlMjBkb2N0b3IlMjBwb3J0cmFpdHxlbnwwfDJ8fHwxNzczNjA1NzM2fDA&ixlib=rb-4.1.0&q=80&w=1080",
  PATIENT_BG_1: "https://images.unsplash.com/photo-1758273240403-052b3c99f636?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwxfHxwYXRpZW50JTIwY29uc3VsdGF0aW9uJTIwY2FsbSUyMHdlbGxuZXNzfGVufDB8MHx8fDE3NzM2MDU3MzZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  PATIENT_BG_2: "https://images.unsplash.com/photo-1758876201548-ade1eff8b169?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwzfHxwYXRpZW50JTIwY29uc3VsdGF0aW9uJTIwY2FsbSUyMHdlbGxuZXNzfGVufDB8MHx8fDE3NzM2MDU3MzZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  PATIENT_BG_3: "https://images.unsplash.com/photo-1758599880788-e49f6ee77bc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwyfHxwYXRpZW50JTIwY29uc3VsdGF0aW9uJTIwY2FsbSUyMHdlbGxuZXNzfGVufDB8MHx8fDE3NzM2MDU3MzZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  PATIENT_BG_4: "https://images.unsplash.com/photo-1767611078839-f4c1e052f673?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw0fHxwYXRpZW50JTIwY29uc3VsdGF0aW9uJTIwY2FsbSUyMHdlbGxuZXNzfGVufDB8MHx8fDE3NzM2MDU3MzZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
} as const;

export type ImageKey = keyof typeof IMAGES;
